class UserAlreadyExistsException(Exception):
  pass

class AuthenticationFailureException(Exception):
  pass